name: Deploy to GitHub Pages

// Instead of pushing built site to the repo, build on GH Actions and deploy that.

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build
      
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2